import { useCallback, useRef } from "react";
import { listServices } from "../../api/services";
import SearchCombobox from "../../components/SearchCombobox";
import { useAuth } from "../../context/AuthContext";
import { isManagerOrAbove } from "../../utils/roles";
import type { Service } from "../../api/types";

// Price/fee/discount fields are "" until the user types a value, so an
// untouched field never silently submits as a real 0 — see emptyLine().
// Quantity is the exception: it starts at a real 1, because every total
// multiplies by it and a blank qty silently zeroed the whole invoice while
// the "1" placeholder made the field look already filled.
// vat_rate follows the price rule: it's pre-filled from the
// business's default VAT rate, but when that default is 0 (as it is until
// someone sets one in Settings) pre-filling a literal "0" put an
// un-clearable zero in the field — typing over it snapped straight back,
// because Number("") is 0. Blank + a "0" placeholder reads the same and
// stays editable.
export interface LineItemState {
  key: string;
  service_id: number | null;
  description: string;
  qty: number | "";
  unit_price: number | "";
  govt_fee: number | "";
  bank_fee: number | "";
  edrh_fee: number | "";
  trans_no: string;
  inv_no: string;
  /** A percentage of the line's gross, not a currency amount. */
  discount_pct: number | "";
  vat_rate: number | "";
  save_as_service: boolean;
  isAdhoc: boolean;
}

export function emptyLine(defaultVat: number): LineItemState {
  return {
    key: crypto.randomUUID(),
    service_id: null,
    description: "",
    // A real 1, not a placeholder — see the note above.
    qty: 1,
    unit_price: "",
    govt_fee: "",
    bank_fee: "",
    edrh_fee: "",
    trans_no: "",
    inv_no: "",
    discount_pct: "",
    // 0 would show as an un-clearable literal zero; blank shows the "0"
    // placeholder instead and still totals as 0.
    vat_rate: defaultVat || "",
    save_as_service: false,
    isAdhoc: false,
  };
}

// Blank qty/unit_price/discount contribute 0 to running totals instead of
// throwing/NaN-ing while the user is still filling the row in; callers that
// build the save payload validate qty/unit_price are actually filled first
// (see InvoiceCreatePage/QuotationCreatePage handleSubmit).
export function num(v: number | ""): number {
  return v === "" ? 0 : v;
}

// The discount is a percentage of the line's gross. Mirrors
// services/invoice_calc.discount_amount on the backend, which is what
// actually gets stored — keep the two in step.
export function lineNet(line: LineItemState): number {
  const gross = num(line.qty) * num(line.unit_price);
  const pct = Math.min(Math.max(num(line.discount_pct), 0), 100);
  return Math.max(gross - gross * (pct / 100), 0);
}

// includeFees mirrors what the HASSAS template actually prints: its Total
// column is fee-inclusive, so the row totals add up to the grand total on the
// page the customer receives. The generic template prints net + VAT only, and
// so does the column here for those businesses.
export function lineTotal(line: LineItemState, includeFees = false) {
  const net = lineNet(line);
  const vat = net * (num(line.vat_rate) / 100);
  const fees = includeFees
    ? (num(line.govt_fee) + num(line.bank_fee) + num(line.edrh_fee)) * num(line.qty)
    : 0;
  return net + vat + fees;
}

export default function LineItemRow({
  line,
  defaultVat,
  showFeeBreakdown = false,
  autoReferences = false,
  onChange,
  onRemove,
}: {
  line: LineItemState;
  defaultVat: number;
  // The Trans No./Inv No./Bank Fee/E-Drh Fee columns only mean anything for
  // a business using the exact HASSAS invoice template — every other
  // business never sees them, matching what actually prints.
  showFeeBreakdown?: boolean;
  // Trans No./Inv No. are generated by the server from the receipt number,
  // which doesn't exist until save — so the inputs are locked, not pre-filled.
  autoReferences?: boolean;
  onChange: (line: LineItemState) => void;
  onRemove: () => void;
}) {
  const { user } = useAuth();
  const rowRef = useRef<HTMLTableRowElement>(null);

  const fetchServices = useCallback(async (query: string) => {
    const res = await listServices({ search: query || undefined, page: 1, page_size: 15 });
    return res.items;
  }, []);

  // Picking a service unmounts the search box it was picked from, which drops
  // focus to <body> and strands anyone working by keyboard. Wait for the row
  // to re-render, then carry on at the named field.
  //
  // setTimeout rather than requestAnimationFrame: rAF callbacks don't run at
  // all while the window is hidden or in a background tab, which silently
  // skipped the focus hand-off.
  function focusField(name: string) {
    setTimeout(() => {
      const el = rowRef.current?.querySelector<HTMLInputElement>(`input[data-field="${name}"]`);
      if (!el) return;
      // focus() first and select() separately: select() on its own does not
      // focus a number input, which left focus on <body> and stranded the
      // keyboard flow one field short.
      el.focus();
      try {
        el.select();
      } catch {
        // Selection isn't supported on every input type; focus is the part
        // that matters.
      }
    }, 0);
  }

  function selectService(s: Service) {
    onChange({
      ...line,
      service_id: s.id,
      description: s.name,
      // If the row's qty was cleared before picking a service, put it back to
      // 1 rather than leaving a service priced at zero.
      qty: line.qty === "" ? 1 : line.qty,
      unit_price: s.price,
      govt_fee: s.govt_fee,
      bank_fee: s.bank_fee,
      edrh_fee: s.edrh_fee,
      vat_rate: s.taxable ? defaultVat || "" : "",
      isAdhoc: false,
      save_as_service: false,
    });
    focusField("qty");
  }

  function switchToAdhoc(query: string) {
    onChange({
      ...line,
      service_id: null,
      description: query,
      isAdhoc: true,
      // The option says "Save as new service", so default to actually doing
      // it — still unticked-able for a genuine one-off. Only a manager or
      // above may create services, and the backend rejects it for anyone
      // else, so don't pre-tick a box they can't see or clear.
      save_as_service: isManagerOrAbove(user?.role),
    });
    focusField("description");
  }

  return (
    <tr ref={rowRef} className="border-b border-line">
      <td className="px-2 py-2 align-top" style={{ minWidth: 220 }}>
        {line.isAdhoc || line.description ? (
          <div>
            <input
              data-field="description"
              value={line.description}
              onChange={(e) => onChange({ ...line, description: e.target.value })}
              className="w-full rounded-md border border-line px-2 py-1 text-sm"
              placeholder={showFeeBreakdown ? "Site name" : "Description"}
            />
            {line.service_id === null && (
              <div className="mt-1 flex items-center gap-2">
                <span className="text-xs text-muted">New service</span>
                {isManagerOrAbove(user?.role) && (
                  <label className="flex items-center gap-1 text-xs text-muted">
                    <input
                      type="checkbox"
                      checked={line.save_as_service}
                      onChange={(e) => onChange({ ...line, save_as_service: e.target.checked })}
                    />
                    Save to services
                  </label>
                )}
              </div>
            )}
          </div>
        ) : (
          <SearchCombobox<Service>
            placeholder="Search service..."
            fetchOptions={fetchServices}
            getLabel={(s) => s.name}
            getSubLabel={(s) => `${s.price.toFixed(2)} + govt ${s.govt_fee.toFixed(2)}`}
            onSelect={selectService}
            extraOption={{
              label: "+ Save as new service",
              onClick: () => switchToAdhoc(""),
            }}
          />
        )}
      </td>
      <td className="px-2 py-2 align-top">
        <input
          data-field="qty"
          type="number"
          min="0"
          step="1"
          placeholder="1"
          value={line.qty}
          onChange={(e) => onChange({ ...line, qty: e.target.value === "" ? "" : Number(e.target.value) })}
          className="w-20 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
        />
      </td>
      {showFeeBreakdown && (
        <>
          <td className="px-2 py-2 align-top">
            <input
              value={autoReferences ? "" : line.trans_no}
              onChange={(e) => onChange({ ...line, trans_no: e.target.value })}
              disabled={autoReferences}
              placeholder={autoReferences ? "Auto" : "Trans No."}
              className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted disabled:cursor-not-allowed disabled:bg-wash-1"
            />
          </td>
          <td className="px-2 py-2 align-top">
            <input
              value={autoReferences ? "" : line.inv_no}
              onChange={(e) => onChange({ ...line, inv_no: e.target.value })}
              disabled={autoReferences}
              placeholder={autoReferences ? "Auto" : "Inv No."}
              className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted disabled:cursor-not-allowed disabled:bg-wash-1"
            />
          </td>
        </>
      )}
      {!showFeeBreakdown && (
        <td className="px-2 py-2 align-top">
          <input
            type="number"
            min="0"
            step="any"
            placeholder="e.g. 1500"
            value={line.unit_price}
            onChange={(e) => onChange({ ...line, unit_price: e.target.value === "" ? "" : Number(e.target.value) })}
            className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
          />
        </td>
      )}
      <td className="px-2 py-2 align-top">
        <input
          type="number"
          min="0"
          step="any"
          placeholder="e.g. 200"
          value={line.govt_fee}
          onChange={(e) => onChange({ ...line, govt_fee: e.target.value === "" ? "" : Number(e.target.value) })}
          className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
        />
      </td>
      {showFeeBreakdown && (
        <>
          <td className="px-2 py-2 align-top">
            <input
              type="number"
              min="0"
              step="any"
              placeholder="0"
              value={line.bank_fee}
              onChange={(e) => onChange({ ...line, bank_fee: e.target.value === "" ? "" : Number(e.target.value) })}
              className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
            />
          </td>
          <td className="px-2 py-2 align-top">
            <input
              type="number"
              min="0"
              step="any"
              placeholder="e.g. 1500"
              value={line.unit_price}
              onChange={(e) => onChange({ ...line, unit_price: e.target.value === "" ? "" : Number(e.target.value) })}
              className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
            />
          </td>
        </>
      )}
      {showFeeBreakdown && (
        <td className="px-2 py-2 align-top">
          <input
            type="number"
            min="0"
            step="any"
            placeholder="0"
            value={line.edrh_fee}
            onChange={(e) => onChange({ ...line, edrh_fee: e.target.value === "" ? "" : Number(e.target.value) })}
            className="w-24 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
          />
        </td>
      )}
      <td className="px-2 py-2 align-top">
        <input
          type="number"
          min="0"
          max="100"
          step="1"
          placeholder="0"
          value={line.discount_pct}
          onChange={(e) => onChange({ ...line, discount_pct: e.target.value === "" ? "" : Number(e.target.value) })}
          className="w-20 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
        />
      </td>
      <td className="px-2 py-2 align-top">
        <input
          type="number"
          min="0"
          step="1"
          placeholder="0"
          value={line.vat_rate}
          onChange={(e) => onChange({ ...line, vat_rate: e.target.value === "" ? "" : Number(e.target.value) })}
          className="w-16 rounded-md border border-line px-2 py-1 text-sm placeholder:text-muted"
        />
      </td>
      <td className="px-2 py-2 text-right align-top text-sm font-medium text-muted">
        {lineTotal(line, showFeeBreakdown).toFixed(2)}
      </td>
      <td className="px-2 py-2 align-top">
        <button type="button" onClick={onRemove} className="text-muted hover:text-danger">
          ✕
        </button>
      </td>
    </tr>
  );
}
